[package]
name = "pc-organize"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pc-core.workspace = true
pc-db.workspace = true
pc-family.workspace = true
pc-image.workspace = true
anyhow.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
