[package]
name = "pc-apply"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pc-core.workspace = true
pc-db.workspace = true
anyhow.workspace = true
rusqlite.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
